/** Figma file mu6Q6rB0Q9Ts6nIFBx8R9X — 쪼인몰 UI v1 (Full Flow frames) */
export const mallColors = {
  canvas: '#f8f9f6',
  adminCanvas: '#f4f6f2',
  surface: '#ffffff',
  surfaceMuted: '#eef1ec',
  surfaceInput: '#fbfcfa',
  border: '#e5e8e3',
  borderCanvas: '#d8ddd6',
  textPrimary: '#17212b',
  textSecondary: '#7d8780',
  accentGreen: '#66b83f',
  accentLime: '#a7e65b',
  accentGreenSoft: '#eff8e7',
  danger: '#e55f5f',
  adminNavy: '#17212b',
  adminNavyActive: '#283440',
  adminNavMuted: '#d9e0da',
} as const;

export const mallMetrics = {
  screenWidth: 390,
  screenPadding: 20,
  gridColumnGap: 8,
  gridRowGap: 12,
  productCardRadius: 18,
  productImageHeight: 160,
  productCardMinHeight: 265,
  productCardBodyPadding: 11,
  productTitleLines: 2,
  productTitleMinHeight: 40,
  badgeHeight: 24,
  badgeRadius: 12,
  badgePaddingH: 10,
  chipHeight: 36,
  chipRadius: 18,
  chipPaddingH: 14,
  chipGap: 8,
  searchHeight: 44,
  searchRadius: 14,
  headerHeight: 72,
  coinPillHeight: 36,
  coinPillRadius: 18,
  detailHeroHeight: 310,
  detailInfoRadius: 18,
  detailInfoPadding: 16,
  detailSectionRadius: 18,
  detailSectionHeight: 110,
  bottomBarHeight: 96,
  ctaHeight: 52,
  ctaRadius: 14,
  sortTextSize: 12,
  titleSize: 24,
  productNameSize: 14,
  productPriceSize: 16,
  detailTitleSize: 22,
  detailPriceSize: 24,
} as const;
