import { assertSafeUiCopy } from './investor-demo-copy.ts';

export type DemoPersonaRole = 'host' | 'player' | 'owner' | 'club';

export type DemoPersonaSpec = {
  slug: string;
  nickname: string;
  gender: 'MALE' | 'FEMALE';
  ageBand: 'TWENTIES' | 'THIRTIES' | 'FORTIES';
  age: number;
  heightCm: number;
  regionLabel: string;
  regionCode: string;
  bio: string;
  skillLevel: 'BEGINNER' | 'INTERMEDIATE' | 'ADVANCED';
  screenHandicap: number;
  fieldHandicap: number;
  attendanceDays: number;
  includeTodayAttendance: boolean;
  hostCompleted: number;
  participateCompleted: number;
  role: DemoPersonaRole;
  visual: string;
};

export const DEMO_PERSONAS: DemoPersonaSpec[] = [
  {
    slug: 'hajun',
    nickname: '정하준',
    gender: 'MALE',
    ageBand: 'THIRTIES',
    age: 34,
    heightCm: 178,
    regionLabel: '서울 강남',
    regionCode: '11680',
    bio: '강남 스크린 주말 번개 호스트. 초보·중급 환영합니다.',
    skillLevel: 'ADVANCED',
    screenHandicap: 4,
    fieldHandicap: 8,
    attendanceDays: 12,
    includeTodayAttendance: true,
    hostCompleted: 5,
    participateCompleted: 1,
    role: 'host',
    visual: 'Korean man 34, short black hair, light stubble, navy knit, cafe window light',
  },
  {
    slug: 'seoa',
    nickname: '윤서아',
    gender: 'FEMALE',
    ageBand: 'TWENTIES',
    age: 27,
    heightCm: 165,
    regionLabel: '경기 성남',
    regionCode: '41135',
    bio: '필드·스크린 가리지 않는 참가 중심 플레이어.',
    skillLevel: 'INTERMEDIATE',
    screenHandicap: 12,
    fieldHandicap: 18,
    attendanceDays: 7,
    includeTodayAttendance: true,
    hostCompleted: 0,
    participateCompleted: 5,
    role: 'player',
    visual: 'Korean woman 27, long wavy dark hair, cream cardigan, outdoor park afternoon',
  },
  {
    slug: 'doyun',
    nickname: '한도윤',
    gender: 'MALE',
    ageBand: 'FORTIES',
    age: 41,
    heightCm: 176,
    regionLabel: '경기 수원',
    regionCode: '41111',
    bio: '스크린 매장 운영. 저녁 타임 매칭을 자주 엽니다.',
    skillLevel: 'INTERMEDIATE',
    screenHandicap: 10,
    fieldHandicap: 14,
    attendanceDays: 5,
    includeTodayAttendance: true,
    hostCompleted: 1,
    participateCompleted: 0,
    role: 'owner',
    visual: 'Korean man 41, thin glasses, neat side part, charcoal shirt, shop interior',
  },
  {
    slug: 'yerin',
    nickname: '최예린',
    gender: 'FEMALE',
    ageBand: 'TWENTIES',
    age: 24,
    heightCm: 162,
    regionLabel: '서울 마포',
    regionCode: '11440',
    bio: '입문 두 달 차. 친한 분위기 조인을 좋아합니다.',
    skillLevel: 'BEGINNER',
    screenHandicap: 28,
    fieldHandicap: 36,
    attendanceDays: 3,
    includeTodayAttendance: true,
    hostCompleted: 0,
    participateCompleted: 2,
    role: 'player',
    visual: 'Korean woman 24, chin-length bob, soft bangs, denim jacket, city street',
  },
  {
    slug: 'minjae',
    nickname: '강민재',
    gender: 'MALE',
    ageBand: 'THIRTIES',
    age: 36,
    heightCm: 181,
    regionLabel: '서울 송파',
    regionCode: '11710',
    bio: '주말 클럽 라운드 총무. 일정 조율을 맡습니다.',
    skillLevel: 'ADVANCED',
    screenHandicap: 6,
    fieldHandicap: 9,
    attendanceDays: 9,
    includeTodayAttendance: false,
    hostCompleted: 1,
    participateCompleted: 2,
    role: 'club',
    visual: 'Korean man 36, athletic build, crew cut, white polo, indoor driving range',
  },
  {
    slug: 'jihu',
    nickname: '배지후',
    gender: 'MALE',
    ageBand: 'THIRTIES',
    age: 31,
    heightCm: 174,
    regionLabel: '인천 연수',
    regionCode: '28185',
    bio: '평일 퇴근 후 스크린 한 게임.',
    skillLevel: 'INTERMEDIATE',
    screenHandicap: 14,
    fieldHandicap: 20,
    attendanceDays: 4,
    includeTodayAttendance: true,
    hostCompleted: 0,
    participateCompleted: 2,
    role: 'player',
    visual: 'Korean man 31, slightly messy hair, olive overshirt, evening city lights',
  },
  {
    slug: 'haneul',
    nickname: '오하늘',
    gender: 'FEMALE',
    ageBand: 'TWENTIES',
    age: 29,
    heightCm: 168,
    regionLabel: '부산 해운대',
    regionCode: '26350',
    bio: '필드 바다 코스를 좋아합니다.',
    skillLevel: 'INTERMEDIATE',
    screenHandicap: 16,
    fieldHandicap: 22,
    attendanceDays: 6,
    includeTodayAttendance: true,
    hostCompleted: 0,
    participateCompleted: 3,
    role: 'player',
    visual: 'Korean woman 29, wind-blown long hair, linen shirt, seaside promenade',
  },
  {
    slug: 'taehyun',
    nickname: '임태현',
    gender: 'MALE',
    ageBand: 'FORTIES',
    age: 44,
    heightCm: 177,
    regionLabel: '경기 용인',
    regionCode: '41461',
    bio: '주말 필드 호스트. 그린피 정산은 명확하게.',
    skillLevel: 'ADVANCED',
    screenHandicap: 5,
    fieldHandicap: 7,
    attendanceDays: 8,
    includeTodayAttendance: true,
    hostCompleted: 5,
    participateCompleted: 0,
    role: 'host',
    visual: 'Korean man 44, mature face, short salt-and-pepper hair, navy golf polo, fairway',
  },
  {
    slug: 'jiho',
    nickname: '송지호',
    gender: 'MALE',
    ageBand: 'TWENTIES',
    age: 28,
    heightCm: 180,
    regionLabel: '서울 마포',
    regionCode: '11440',
    bio: '홍대 근처 저녁 스크린을 자주 갑니다.',
    skillLevel: 'INTERMEDIATE',
    screenHandicap: 15,
    fieldHandicap: 21,
    attendanceDays: 5,
    includeTodayAttendance: true,
    hostCompleted: 0,
    participateCompleted: 0,
    role: 'player',
    visual: 'Korean man 28, soft perm, black tee, brick cafe wall',
  },
  {
    slug: 'dohyun',
    nickname: '권도현',
    gender: 'MALE',
    ageBand: 'THIRTIES',
    age: 33,
    heightCm: 176,
    regionLabel: '경기 고양',
    regionCode: '41285',
    bio: '일산 쪽 평일 야간 호스트입니다.',
    skillLevel: 'ADVANCED',
    screenHandicap: 8,
    fieldHandicap: 12,
    attendanceDays: 8,
    includeTodayAttendance: true,
    hostCompleted: 2,
    participateCompleted: 0,
    role: 'host',
    visual: 'Korean man 33, undercut, gray hoodie, lakeside walkway',
  },
  {
    slug: 'daeun',
    nickname: '김다은',
    gender: 'FEMALE',
    ageBand: 'TWENTIES',
    age: 26,
    heightCm: 164,
    regionLabel: '서울 송파',
    regionCode: '11710',
    bio: '잠실에서 가볍게 치는 걸 좋아합니다.',
    skillLevel: 'BEGINNER',
    screenHandicap: 26,
    fieldHandicap: 34,
    attendanceDays: 4,
    includeTodayAttendance: true,
    hostCompleted: 0,
    participateCompleted: 0,
    role: 'player',
    visual: 'Korean woman 26, high ponytail, white blouse, sunny riverside',
  },
  {
    slug: 'subin',
    nickname: '이수빈',
    gender: 'FEMALE',
    ageBand: 'THIRTIES',
    age: 31,
    heightCm: 167,
    regionLabel: '인천 부평',
    regionCode: '28237',
    bio: '인천 평일 저녁 조인을 자주 찾습니다.',
    skillLevel: 'INTERMEDIATE',
    screenHandicap: 14,
    fieldHandicap: 20,
    attendanceDays: 6,
    includeTodayAttendance: false,
    hostCompleted: 0,
    participateCompleted: 0,
    role: 'player',
    visual: 'Korean woman 31, shoulder-length straight hair, beige trench, subway exit daylight',
  },
  {
    slug: 'junhyuk',
    nickname: '남준혁',
    gender: 'MALE',
    ageBand: 'THIRTIES',
    age: 38,
    heightCm: 182,
    regionLabel: '경기 용인',
    regionCode: '41465',
    bio: '수지·죽전 스크린을 자주 엽니다.',
    skillLevel: 'ADVANCED',
    screenHandicap: 7,
    fieldHandicap: 11,
    attendanceDays: 10,
    includeTodayAttendance: true,
    hostCompleted: 2,
    participateCompleted: 0,
    role: 'host',
    visual: 'Korean man 38, square jaw, short fade, black windbreaker, parking lot dusk',
  },
  {
    slug: 'siwoo',
    nickname: '황시우',
    gender: 'MALE',
    ageBand: 'TWENTIES',
    age: 25,
    heightCm: 175,
    regionLabel: '서울 강서',
    regionCode: '11500',
    bio: '입문 반 년. 천천히 알려 주시는 분 환영.',
    skillLevel: 'BEGINNER',
    screenHandicap: 30,
    fieldHandicap: 36,
    attendanceDays: 3,
    includeTodayAttendance: true,
    hostCompleted: 0,
    participateCompleted: 0,
    role: 'player',
    visual: 'Korean man 25, round glasses, hoodie, indoor practice bay',
  },
  {
    slug: 'yewon',
    nickname: '정예원',
    gender: 'FEMALE',
    ageBand: 'THIRTIES',
    age: 35,
    heightCm: 166,
    regionLabel: '경기 성남',
    regionCode: '41135',
    bio: '분당에서 주말 오전에 자주 칩니다.',
    skillLevel: 'INTERMEDIATE',
    screenHandicap: 13,
    fieldHandicap: 18,
    attendanceDays: 7,
    includeTodayAttendance: true,
    hostCompleted: 0,
    participateCompleted: 0,
    role: 'player',
    visual: 'Korean woman 35, low bun, gold hoop earrings, sunlit kitchen',
  },
  {
    slug: 'soyun',
    nickname: '한소윤',
    gender: 'FEMALE',
    ageBand: 'TWENTIES',
    age: 28,
    heightCm: 163,
    regionLabel: '경기 수원',
    regionCode: '41113',
    bio: '수원 저녁 타임 위주로 참가합니다.',
    skillLevel: 'INTERMEDIATE',
    screenHandicap: 17,
    fieldHandicap: 23,
    attendanceDays: 5,
    includeTodayAttendance: true,
    hostCompleted: 0,
    participateCompleted: 0,
    role: 'player',
    visual: 'Korean woman 28, curtain bangs, knit vest, bookstore aisle',
  },
  {
    slug: 'seongmin',
    nickname: '문성민',
    gender: 'MALE',
    ageBand: 'FORTIES',
    age: 42,
    heightCm: 173,
    regionLabel: '경기 화성',
    regionCode: '41590',
    bio: '동탄 매장 운영. 주중 저녁 매칭을 엽니다.',
    skillLevel: 'INTERMEDIATE',
    screenHandicap: 11,
    fieldHandicap: 16,
    attendanceDays: 6,
    includeTodayAttendance: true,
    hostCompleted: 1,
    participateCompleted: 0,
    role: 'owner',
    visual: 'Korean man 42, receding hairline kept neat, navy shirt, reception counter',
  },
  {
    slug: 'woojin',
    nickname: '장우진',
    gender: 'MALE',
    ageBand: 'TWENTIES',
    age: 29,
    heightCm: 179,
    regionLabel: '경기 김포',
    regionCode: '41570',
    bio: '김포 구래에서 평일 야간으로 모입니다.',
    skillLevel: 'INTERMEDIATE',
    screenHandicap: 16,
    fieldHandicap: 22,
    attendanceDays: 4,
    includeTodayAttendance: false,
    hostCompleted: 0,
    participateCompleted: 0,
    role: 'player',
    visual: 'Korean man 29, beard stubble, flannel shirt, riverside bike path',
  },
  {
    slug: 'jimin',
    nickname: '신지민',
    gender: 'FEMALE',
    ageBand: 'TWENTIES',
    age: 23,
    heightCm: 160,
    regionLabel: '서울 관악',
    regionCode: '11620',
    bio: '대학 근처 스크린 입문. 편한 분위기 좋아합니다.',
    skillLevel: 'BEGINNER',
    screenHandicap: 32,
    fieldHandicap: 36,
    attendanceDays: 2,
    includeTodayAttendance: true,
    hostCompleted: 0,
    participateCompleted: 0,
    role: 'player',
    visual: 'Korean woman 23, airy bangs, college backpack, campus autumn trees',
  },
  {
    slug: 'chaewon',
    nickname: '윤채원',
    gender: 'FEMALE',
    ageBand: 'THIRTIES',
    age: 32,
    heightCm: 169,
    regionLabel: '경기 안양',
    regionCode: '41173',
    bio: '평촌에서 주중 저녁 한 게임.',
    skillLevel: 'ADVANCED',
    screenHandicap: 9,
    fieldHandicap: 13,
    attendanceDays: 8,
    includeTodayAttendance: true,
    hostCompleted: 1,
    participateCompleted: 0,
    role: 'host',
    visual: 'Korean woman 32, sleek long hair, black athletic zip, rooftop golden hour',
  },
  {
    slug: 'taeyang',
    nickname: '서태양',
    gender: 'MALE',
    ageBand: 'THIRTIES',
    age: 36,
    heightCm: 184,
    regionLabel: '경기 남양주',
    regionCode: '41360',
    bio: '다산·별내 스크린 호스트. 정시 시작 지킵니다.',
    skillLevel: 'ADVANCED',
    screenHandicap: 6,
    fieldHandicap: 10,
    attendanceDays: 9,
    includeTodayAttendance: true,
    hostCompleted: 2,
    participateCompleted: 0,
    role: 'host',
    visual: 'Korean man 36, tall, buzzed sides, charcoal coat, apartment lobby',
  },
  {
    slug: 'eunseo',
    nickname: '조은서',
    gender: 'FEMALE',
    ageBand: 'TWENTIES',
    age: 27,
    heightCm: 165,
    regionLabel: '경기 의정부',
    regionCode: '41150',
    bio: '의정부 민락에서 주말 오전에 참가합니다.',
    skillLevel: 'INTERMEDIATE',
    screenHandicap: 18,
    fieldHandicap: 24,
    attendanceDays: 5,
    includeTodayAttendance: true,
    hostCompleted: 0,
    participateCompleted: 0,
    role: 'player',
    visual: 'Korean woman 27, warm smile, knit beanie in hand, morning cafe terrace',
  },
  {
    slug: 'seungho',
    nickname: '백승호',
    gender: 'MALE',
    ageBand: 'FORTIES',
    age: 40,
    heightCm: 178,
    regionLabel: '충남 천안',
    regionCode: '44131',
    bio: '주말 필드 부킹을 자주 잡습니다.',
    skillLevel: 'ADVANCED',
    screenHandicap: 7,
    fieldHandicap: 9,
    attendanceDays: 7,
    includeTodayAttendance: false,
    hostCompleted: 2,
    participateCompleted: 0,
    role: 'host',
    visual: 'Korean man 40, calm eyes, navy vest over white shirt, clubhouse porch',
  },
  {
    slug: 'jaewon',
    nickname: '고재원',
    gender: 'MALE',
    ageBand: 'THIRTIES',
    age: 30,
    heightCm: 177,
    regionLabel: '강원 춘천',
    regionCode: '51110',
    bio: '강원 라운드도 마다하지 않습니다.',
    skillLevel: 'INTERMEDIATE',
    screenHandicap: 15,
    fieldHandicap: 19,
    attendanceDays: 4,
    includeTodayAttendance: true,
    hostCompleted: 0,
    participateCompleted: 0,
    role: 'player',
    visual: 'Korean man 30, sun-kissed, fleece pullover, lake trail pines',
  },
  {
    slug: 'sua',
    nickname: '배수아',
    gender: 'FEMALE',
    ageBand: 'THIRTIES',
    age: 34,
    heightCm: 164,
    regionLabel: '경기 파주',
    regionCode: '41480',
    bio: '운정에서 평일 저녁 스크린을 찾습니다.',
    skillLevel: 'INTERMEDIATE',
    screenHandicap: 16,
    fieldHandicap: 22,
    attendanceDays: 6,
    includeTodayAttendance: true,
    hostCompleted: 0,
    participateCompleted: 0,
    role: 'player',
    visual: 'Korean woman 34, soft waves, camel coat, quiet residential street',
  },
  {
    slug: 'harin',
    nickname: '임하린',
    gender: 'FEMALE',
    ageBand: 'TWENTIES',
    age: 22,
    heightCm: 161,
    regionLabel: '서울 용산',
    regionCode: '11170',
    bio: '용산·이태원 근처 번개를 좋아합니다.',
    skillLevel: 'BEGINNER',
    screenHandicap: 29,
    fieldHandicap: 36,
    attendanceDays: 3,
    includeTodayAttendance: true,
    hostCompleted: 0,
    participateCompleted: 0,
    role: 'player',
    visual: 'Korean woman 22, lively eyes, cropped jacket, Han river park',
  },
  {
    slug: 'yujin',
    nickname: '오유진',
    gender: 'FEMALE',
    ageBand: 'THIRTIES',
    age: 38,
    heightCm: 166,
    regionLabel: '대전 서구',
    regionCode: '30170',
    bio: '대전 둔산 스크린과 주말 필드를 오갑니다.',
    skillLevel: 'INTERMEDIATE',
    screenHandicap: 14,
    fieldHandicap: 18,
    attendanceDays: 6,
    includeTodayAttendance: true,
    hostCompleted: 1,
    participateCompleted: 0,
    role: 'host',
    visual: 'Korean woman 38, elegant short hair, silk blouse, hotel lobby light',
  },
  {
    slug: 'seohyun',
    nickname: '유시현',
    gender: 'MALE',
    ageBand: 'TWENTIES',
    age: 27,
    heightCm: 181,
    regionLabel: '대구 수성',
    regionCode: '27260',
    bio: '대구 수성에서 주말 오전 스크린.',
    skillLevel: 'INTERMEDIATE',
    screenHandicap: 13,
    fieldHandicap: 19,
    attendanceDays: 4,
    includeTodayAttendance: true,
    hostCompleted: 0,
    participateCompleted: 0,
    role: 'player',
    visual: 'Korean man 27, clean fade, white sneakers vibe, sunny plaza',
  },
];

export type DemoPersonaSlug = (typeof DEMO_PERSONAS)[number]['slug'];

export const DEMO_PERSONA_SLUGS = DEMO_PERSONAS.map((row) => row.slug);

export function listHostSlugs(): DemoPersonaSlug[] {
  return DEMO_PERSONAS.filter((row) => row.role === 'host' || row.role === 'owner' || row.role === 'club').map(
    (row) => row.slug,
  );
}

export function listPlayerSlugs(): DemoPersonaSlug[] {
  return DEMO_PERSONAS.map((row) => row.slug);
}

export function validatePersonaCatalog(): void {
  const slugs = new Set<string>();
  const names = new Set<string>();
  for (const persona of DEMO_PERSONAS) {
    if (slugs.has(persona.slug)) throw new Error(`duplicate_persona_slug ${persona.slug}`);
    if (names.has(persona.nickname)) throw new Error(`duplicate_persona_name ${persona.nickname}`);
    slugs.add(persona.slug);
    names.add(persona.nickname);
    assertSafeUiCopy(persona.nickname, `persona.${persona.slug}.nickname`);
    assertSafeUiCopy(persona.bio, `persona.${persona.slug}.bio`);
    assertSafeUiCopy(persona.regionLabel, `persona.${persona.slug}.region`);
  }
}
