apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'expo.modules.jjoinkakaomap'
version = '1.0.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
if (expoModulesCorePlugin.exists()) {
  apply from: expoModulesCorePlugin
  applyKotlinExpoModulesCorePlugin()
  useDefaultAndroidSdkVersions()
  useExpoPublishing()
}

android {
  namespace "expo.modules.jjoinkakaomap"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
  }
  lintOptions {
    abortOnError false
  }
}

repositories {
  maven { url 'https://devrepo.kakao.com/nexus/repository/kakaomap-releases/' }
}

dependencies {
  implementation project(':expo-modules-core')
  implementation 'com.kakao.maps.open:android:2.15.1'
}
