import type { ExploreVenueDto } from '@jjoin/types';
import { exploreConfig } from '../presence/presence.config';

const { demoCenter } = exploreConfig;

/** Geoje-area fixture venues — Map/Join/Presence are not blocked by Venue Provider. */
export const MOCK_EXPLORE_VENUES: ExploreVenueDto[] = [
  {
    venueId: 'venue_sg_geoje',
    name: 'SG골프 거제점',
    address: '거제시 고현동',
    regionLabel: '거제시 고현동',
    latitude: demoCenter.latitude + 0.004,
    longitude: demoCenter.longitude - 0.006,
    distanceMeters: null,
    openJoinCount: 2,
    joinPreviews: [
      {
        joinId: 'join_sg_1300',
        startAt: new Date().toISOString().slice(0, 10) + 'T13:00:00+09:00',
        scheduledEndAt: new Date().toISOString().slice(0, 10) + 'T17:00:00+09:00',
        currentParticipants: 1,
        maxParticipants: 4,
        rewardCoin: '20',
        hostNickname: '김진우',
        hostVerified: true,
      },
      {
        joinId: 'join_sg_1700',
        startAt: new Date().toISOString().slice(0, 10) + 'T17:00:00+09:00',
        scheduledEndAt: new Date().toISOString().slice(0, 10) + 'T21:00:00+09:00',
        currentParticipants: 2,
        maxParticipants: 4,
        rewardCoin: '10',
        hostNickname: '버디킴',
        hostVerified: true,
      },
    ],
  },
  {
    venueId: 'venue_golfzon_gohyeon',
    name: '골프존 고현점',
    address: '거제시 고현동',
    regionLabel: '거제시 고현동',
    latitude: demoCenter.latitude + 0.002,
    longitude: demoCenter.longitude + 0.003,
    distanceMeters: null,
    openJoinCount: 1,
    joinPreviews: [
      {
        joinId: 'join_gz_1500',
        startAt: new Date().toISOString().slice(0, 10) + 'T15:00:00+09:00',
        scheduledEndAt: new Date().toISOString().slice(0, 10) + 'T19:00:00+09:00',
        currentParticipants: 2,
        maxParticipants: 4,
        rewardCoin: '10',
        hostNickname: '골프왕77',
        hostVerified: true,
      },
    ],
  },
  {
    venueId: 'venue_screenpark',
    name: '거제 스크린파크',
    address: '거제시 장평동',
    regionLabel: '거제시 장평동',
    latitude: demoCenter.latitude - 0.003,
    longitude: demoCenter.longitude - 0.002,
    distanceMeters: null,
    openJoinCount: 0,
    joinPreviews: [],
  },
  {
    venueId: 'venue_kakao_okpo',
    name: '카카오골프 옥포점',
    address: '거제시 옥포동',
    regionLabel: '거제시 옥포동',
    latitude: demoCenter.latitude + 0.008,
    longitude: demoCenter.longitude + 0.007,
    distanceMeters: null,
    openJoinCount: 2,
    joinPreviews: [
      {
        joinId: 'join_ok_1100',
        startAt: new Date().toISOString().slice(0, 10) + 'T11:00:00+09:00',
        scheduledEndAt: new Date().toISOString().slice(0, 10) + 'T14:00:00+09:00',
        currentParticipants: 3,
        maxParticipants: 4,
        rewardCoin: '15',
        hostNickname: '버디킴',
        hostVerified: false,
      },
      {
        joinId: 'join_ok_1800',
        startAt: new Date().toISOString().slice(0, 10) + 'T18:00:00+09:00',
        scheduledEndAt: new Date().toISOString().slice(0, 10) + 'T22:00:00+09:00',
        currentParticipants: 1,
        maxParticipants: 4,
        rewardCoin: '20',
        hostNickname: '김진우',
        hostVerified: true,
      },
    ],
  },
  {
    venueId: 'venue_sg_jangseung',
    name: 'SG골프 장승포점',
    address: '거제시 장승포동',
    regionLabel: '거제시 장승포동',
    latitude: demoCenter.latitude - 0.007,
    longitude: demoCenter.longitude + 0.01,
    distanceMeters: null,
    openJoinCount: 1,
    joinPreviews: [
      {
        joinId: 'join_js_1600',
        startAt: new Date().toISOString().slice(0, 10) + 'T16:00:00+09:00',
        scheduledEndAt: new Date().toISOString().slice(0, 10) + 'T20:00:00+09:00',
        currentParticipants: 1,
        maxParticipants: 4,
        rewardCoin: '12',
        hostNickname: '골프왕77',
        hostVerified: true,
      },
    ],
  },
  {
    venueId: 'venue_park_aje',
    name: '에이원 스크린 아주점',
    address: '거제시 아주동',
    regionLabel: '거제시 아주동',
    latitude: demoCenter.latitude + 0.001,
    longitude: demoCenter.longitude - 0.01,
    distanceMeters: null,
    openJoinCount: 0,
    joinPreviews: [],
  },
];
