-- Billing lifecycle notification types

ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'COIN_PURCHASE_COMPLETED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PREMIUM_SUBSCRIPTION_ACTIVATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PREMIUM_RENEWAL_SUCCEEDED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PREMIUM_RENEWAL_FAILED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PREMIUM_CANCEL_SCHEDULED';
